### ISSUE TITLE
Process.ReadEnvironmentVariables() sometimes causes System.IO.EndOfStreamException : Attempted to read past the end of the stream.

### ISSUE THREAD

**Issue by marbletravis** [gapotchenko/Gapotchenko.FX#2]
I am getting the following exception 

`      Message: 
        System.IO.EndOfStreamException : Attempted to read past the end of the stream.
      Stack Trace: 
        ProcessBinaryReader.ReadCString()
        ProcessEnvironment._ReadEnv(ProcessBinaryReader br)
        ProcessEnvironment._ReadVariablesCore(IntPtr hProcess)
        ProcessEnvironment.ReadVariables(Process process)
        ImplementationAdapter.ReadProcessEnvironmentVariables(Process process)
        ProcessExtensions.ReadEnvironmentVariables(Process process)
`

From my code:

`
var oldProcesses = Process.GetProcesses()
	.Where(x => x.ProcessName.Contains("dotnet")) && x.ReadEnvironmentVariables().ContainsKey("...")).ToList();
`

I am using version 2020.1.15 of the nuget package. I only see the error occasionally, I have tried to find something that distinguishes the errored process from other processes and have to yet find anything. 

Thanks

**Comment by hrumhurum** [comment]
From what I can tell, this looks like a race condition between the process initialization performed by OS and `ReadEnvironmentVariables` function.

In this way, `ReadEnvironmentVariables` tries to read the environment variables block of a process which is not fully formed yet, hence `EndOfStreamException`.

We'll try to come up with a solution for this behavior but it really comes down to the OS level. In meanwhile, a useful strategy to overcome the issue would be to perform several retries before giving up. There is a good package for that: https://github.com/App-vNext/Polly

I will come up with an update once a worthy solution is found and ready.

**Comment by marbletravis** [comment]
@hrumhurum Thanks for the information. I spent some more time analyzing my issue, in my case it was only one out of a handful of processes that my code is managing that would give that error. Unfortunately, that error would happen no matter how many times I re-tried. Given that my code is to support end to end testing, and is therefore a developer tool, its not a big deal to just ignore.

I am going to close this issue, hope that's ok.

**Comment by hrumhurum** [comment]
> error would happen no matter how many times I re-tried

Thank you for pointing that interesting detail out. We'll take a closer look on corresponding code path. Such behavior clearly signifies a bug in `ReadEnvironmentVariables` implementation.

**Comment by dlamkins** [comment]
Hello, I wanted to report that our project is also now encountering this issue.  Likewise retrying resulted in the same exception until the target application was restarted.

> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Gapotchenko.FX.Diagnostics.Implementation.ProcessBinaryReader.ReadCString()
   at Gapotchenko.FX.Diagnostics.Implementation.Windows.ProcessEnvironment._ReadEnv(ProcessBinaryReader br)
   at Gapotchenko.FX.Diagnostics.Implementation.Windows.ProcessEnvironment._ReadVariablesCore(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Implementation.Windows.ImplementationAdapter.ReadProcessEnvironmentVariables(Process process)

**Comment by hrumhurum** [comment]
We tried to reproduce this issue locally, but it always worked.

Are there specific conditions the error appears at? Like the bitness of a host process, target process, and host OS. Exact host OS version etc. Having this information will help.

**Comment by dlamkins** [comment]
I apologize, I recognize that this +1 report is a bit less than helpful as presented.  We had a user report this and confirm that it worked after restarting the process (restarting the application which would cause it to reattempt was not working), so we don't have a whole lot of info, but if it does end up being of any help, here is what we gathered:

Windows 11 Pro, Version 21H2, OS Build 22000.194.
Process is Guild Wars 2 (a game) - 64-bit client.

If there is any further information we can gather the next time this is observed, please let me know.  We've only encountered it once so far in many thousands of runs among different systems, so it certainly doesn't seem common.  In the meantime, we will be catching the exception and handling it accordingly as it's more a QoL feature and not one critical to the application.

**Comment by hrumhurum** [comment]
Fixed in [Gapotchenko.FX 2022.1 (Release build 2022.1.4)](https://github.com/gapotchenko/Gapotchenko.FX/releases/tag/v2022.1.4).
